### ISSUE TITLE
Better conversion from WikiSource

### ISSUE THREAD

**Issue by TomazErjavec** [COST-ELTeC/ELTeC-slv#5]
Current conversion of Slovene WikiSource novels downloads mark-down and converts it into TEI ELTeC using a Perl script to first slightly fix the MD, and then with the TEI markdowntotei stylesheet.

However, the MD novels contain also lost of extra mark-up, either XML (mostly HTML tags, but also e.g. `<poem>`), markup in curly brackets (`{{...}}`) and metadata in square brackets (`[[...]]`), This markup is discarded, although it would be useful for ELTeC in two cases: poems and notes. The first are currently converted to a series of paragraphs, while notes are removed. A proper conversion would be even more useful for more richly annotated TEI books (as those in IMP).

However, such a conversion would be quite challenging to implement, esp. as there is no guarantee, that such markup is even syntactically correct. I leave this issue here in case we ever find somebody to to it properly.

**Comment by TomazErjavec** [comment]
Closing this issue, as it doesn't seem we will find anybody to add such markup.

**Comment by lb42** [comment]
I could have a look if you like

**Comment by TomazErjavec** [comment]
Sure, if you can! But, as said, it would be messy, as there is no syntactic control on the source. Also, I now use a somewhat messy pipeline for converting the Wiki books - however, on the plus side, all the scripts are in git. Let me know if you need any help.

**Comment by TomazErjavec** [comment]
This doesn't seem to be happening, so, closing again.
